import React from "react";
import LegalPage from "./LegalPage";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";

const CookiesPolicy = () => {
  return (
    <LegalPage
      biggerRight
      left={() => (
        <Box
          display={"flex"}
          flexDirection={"column"}
          className={"layout-content-padding"}
        >
          <Typography variant={"h2"} sx={{ fontWeight: "bold", mb: 4 }}>
            Cookies policy
          </Typography>
        </Box>
      )}
      right={() => (
        <Box
          display={"flex"}
          flexDirection={"column"}
          className={"layout-content-padding"}
        >
          <Typography variant={"caption"} gutterBottom>
            We gather and use information as indicated in our Legal Notice. One
            of the ways we gather information is through the use of the
            technology called “cookies”. At World Delete, we use cookies for
            various things.
          </Typography>
        </Box>
      )}
      content={() => (
        <Box
          display={"flex"}
          flexDirection={"column"}
          className={"layout-content-padding"}
          sx={{
            bgcolor: (theme) => theme.palette.common.white,
            color: (theme) => theme.palette.common.black,
          }}
        >
          <Paragraph
            title={"What is a cookie?"}
            content={
              "A cookie is a small quantity of text that is saved by your browser (like Google Chrome or Apple Safari) when you surf the majority of websites."
            }
          />
          <Paragraph
            title={"What ISN’T a cookie?"}
            content={
              "It’s not a virus, or a trojan or a worm. Nor is it spam, spyware or capable of opening pop-up windows."
            }
          />
          <Paragraph
            title={"What information is saved in a cookie?"}
            content={
              "Cookies don’t tend to save sensitive information about you, like credit card numbers or bank information, photographs or personal information, etc.\n" +
              "The data that is saved is of technical character, statistics, personal preferences, content personalisation, etc.\n" +
              "The web server doesn’t identify you as a person, but through your browser. In fact, if you regularly surf with Google Chrome and try to go to the same website with the Firefox browser, you’ll see that the web doesn’t realise you are the same person because, in reality you are associated with the browser information and not as a person."
            }
          />
          <Paragraph
            title={"What type of cookies exist?"}
            content={
              "Technical Cookies: These are the simplest and allow, among other things, to know when a person or automated application is surfing the web, when an anonymous or registered person is surfing, basic tasks that allow for functioning of a dynamic web.\n" +
              "Analysis Cookies: They collect information about the type of surfing that is occurring, the most used sections, consulted products, schedule of usage, language, etc.\n" +
              "Publicity Cookies: They show adverts based on your surfing habits, what country to are in, language, etc."
            }
          />
          <Paragraph
            title={"What are first-party cookies and those of third parties?"}
            content={
              "Individual cookies are generated by the page you are visiting and those of third parties are generated by external services and providers like Mailchimp, Mailrelay, Facebook, Twitter, Google adsense, etc."
            }
          />
          <Paragraph
            title={"What cookies are used on this website?"}
            content={
              "This web uses its own cookies and those of third parties. On this website, we use the following cookies."
            }
          />
          <Paragraph
            title={"Third-party cookies"}
            content={
              "This website uses analysis services, specifically from Google Analytics, to help us analyse how our users use the website and to become more user friendly. We will never share any data that could identify the user. Google Analytics is an analytical service provided by Google, Inc. You can consult the type of cookies used by Google here."
            }
          />
          <Paragraph
            title={
              "Information about the way to disactivate or delete declared cookies on the main browsers."
            }
            content={
              "You can allow, block or eliminate cookies installed on your computer with the configuration option of your installed browser."
            }
          />
          <Paragraph
            title={"Firefox"}
            content={
              "https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we"
            }
          />
          <Paragraph
            title={"Chrome"}
            content={"https://support.google.com/chrome/answer/95647?hl=es"}
          />
          <Paragraph
            title={"Internet Explorer"}
            content={
              "https://support.microsoft.com/es-es/windows/eliminar-y-administrar-cookies-168dab11-0753-043d-7c16-ede5947fc64d"
            }
          />
          <Paragraph
            title={"Safari"}
            content={
              "https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"
            }
          />
        </Box>
      )}
    />
  );
};

function Paragraph({ title, content }) {
  return (
    <>
      <Typography variant={"h3"} sx={{ mb: 2 }}>
        {title}
      </Typography>
      <Typography variant={"body2"} sx={{ mb: 4, width: "80%" }}>
        {content}
      </Typography>
    </>
  );
}

export default CookiesPolicy;
